"use client";

import { useMemo, useState } from "react";
import {
  exportMessagesAsJson,
  formatDate,
  formatShortDate,
  isTargetGroup,
  parseWhatsAppExport,
  type ParsedChat,
  type WhatsAppMessage,
} from "@/lib/whatsapp";

const TARGET_GROUP = "Zero to One";

type ParsedState = {
  chat: ParsedChat;
  fileName: string;
};

export default function Home() {
  const [parsedState, setParsedState] = useState<ParsedState | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [filterQuery, setFilterQuery] = useState("");
  const [selectedAuthors, setSelectedAuthors] = useState<string[]>([]);
  const [overrideGroup, setOverrideGroup] = useState<string>(TARGET_GROUP);
  const [isLoading, setIsLoading] = useState(false);

  const detectedGroup = parsedState?.chat.groupName ?? null;
  const normalizedOverride = overrideGroup.trim().toLowerCase();
  const overrideMatchesTarget =
    normalizedOverride.length > 0 &&
    normalizedOverride === TARGET_GROUP.toLowerCase();
  const autoMatchesTarget = isTargetGroup(detectedGroup);
  const showConversation =
    Boolean(parsedState) && (autoMatchesTarget || overrideMatchesTarget);

  const participants = parsedState?.chat.participants ?? [];

  const filteredMessages = useMemo(() => {
    if (!parsedState) {
      return [];
    }

    let messages = parsedState.chat.messages;

    if (selectedAuthors.length) {
      messages = messages.filter(
        (msg) => msg.author && selectedAuthors.includes(msg.author)
      );
    }

    if (filterQuery.trim()) {
      const terms = filterQuery.trim().toLowerCase();
      messages = messages.filter(
        (msg) =>
          msg.text.toLowerCase().includes(terms) ||
          (msg.author ?? "").toLowerCase().includes(terms)
      );
    }

    return messages;
  }, [parsedState, selectedAuthors, filterQuery]);

  const handleFiles = async (files: FileList | null) => {
    if (!files?.length) {
      return;
    }

    const file = Array.from(files).find((item) =>
      item.name.toLowerCase().endsWith(".txt")
    );

    if (!file) {
      setError("Please select the .txt export generated by WhatsApp.");
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const text = await file.text();
      const chat = parseWhatsAppExport(text);
      setParsedState({
        chat,
        fileName: file.name,
      });
      setSelectedAuthors([]);
      setFilterQuery("");
      setOverrideGroup(chat.groupName ?? TARGET_GROUP);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong while parsing the chat file."
      );
      setParsedState(null);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = (messages: WhatsAppMessage[]) => {
    const payload = exportMessagesAsJson(messages);
    const blob = new Blob([payload], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    const baseName = parsedState?.fileName.replace(/\.txt$/i, "") ?? "chat";
    link.download = `${baseName}-zero-to-one.json`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const statusLabel = (() => {
    if (!parsedState) {
      return "Upload the exported chat file to begin.";
    }
    if (autoMatchesTarget || overrideMatchesTarget) {
      return "Conversation verified for Zero to One.";
    }
    if (!parsedState.chat.groupName) {
      return "Could not detect the group name automatically. Confirm it below.";
    }
    return `Detected group “${parsedState.chat.groupName}”. Update below if this is the Zero to One chat.`;
  })();

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <section className="mx-auto flex w-full max-w-6xl flex-col gap-8 px-4 pb-20 pt-16 lg:px-8">
        <header>
          <p className="text-sm uppercase tracking-[0.35em] text-indigo-400">
            Zero to One Archive
          </p>
          <h1 className="mt-2 text-4xl font-semibold sm:text-5xl">
            Extract your WhatsApp group conversation.
          </h1>
          <p className="mt-4 max-w-2xl text-base text-slate-300">
            Import the WhatsApp export for <strong>{TARGET_GROUP}</strong> and
            instantly explore every message, keyword, and participant in a clean
            timeline built for quick investigation.
          </p>
        </header>

        <div className="grid gap-6 lg:grid-cols-[1.75fr_minmax(240px,1fr)]">
          <div className="flex flex-col gap-6">
            <UploadPanel
              isLoading={isLoading}
              onFiles={handleFiles}
              status={statusLabel}
              error={error}
            />

            {parsedState && (
              <>
                <VerificationPanel
                  detectedGroup={parsedState.chat.groupName}
                  overrideGroup={overrideGroup}
                  onOverrideChange={setOverrideGroup}
                  autoMatches={autoMatchesTarget}
                  overrideMatches={overrideMatchesTarget}
                />

                {showConversation ? (
                  <ConversationPanel
                    fileName={parsedState.fileName}
                    chat={parsedState.chat}
                    filterQuery={filterQuery}
                    onFilterChange={setFilterQuery}
                    participants={participants}
                    selectedAuthors={selectedAuthors}
                    onSelectionChange={setSelectedAuthors}
                    messages={filteredMessages}
                    onDownload={() => handleDownload(filteredMessages)}
                  />
                ) : (
                  <MismatchNotice />
                )}
              </>
            )}
          </div>

          <aside className="h-fit rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur">
            <h2 className="text-lg font-semibold text-white">
              Need a WhatsApp export?
            </h2>
            <ol className="mt-4 list-decimal space-y-3 pl-6 text-sm text-slate-200">
              <li>Open the WhatsApp group on your phone.</li>
              <li>Tap More &gt; Export chat &gt; Without media.</li>
              <li>Send the file to your computer and upload the .txt here.</li>
            </ol>
            <div className="mt-6 rounded-lg border border-indigo-500/20 bg-indigo-500/10 p-4 text-xs text-indigo-200">
              Tip: This extractor only publishes data locally in your browser.
              Nothing is uploaded to a server.
            </div>
          </aside>
        </div>
      </section>
    </main>
  );
}

type UploadPanelProps = {
  isLoading: boolean;
  onFiles: (files: FileList | null) => void;
  status: string;
  error: string | null;
};

function UploadPanel({ isLoading, onFiles, status, error }: UploadPanelProps) {
  return (
    <div className="rounded-2xl border border-dashed border-indigo-400/40 bg-white/5 p-8 transition hover:border-indigo-400/60">
      <label
        htmlFor="chat-upload"
        className="flex cursor-pointer flex-col items-center gap-4 text-center"
      >
        <span className="rounded-full bg-indigo-500/20 px-4 py-1 text-xs font-medium uppercase tracking-widest text-indigo-200">
          Upload WhatsApp Export
        </span>
        <p className="text-lg font-medium text-white">
          Drag & drop your .txt file or click to browse.
        </p>
        <p className="max-w-xl text-sm text-slate-300">
          The parser supports the standard WhatsApp export format from Android
          and iOS. Attach media is optional—this tool focuses on text content.
        </p>
        <input
          id="chat-upload"
          type="file"
          accept=".txt"
          className="hidden"
          disabled={isLoading}
          onChange={(event) => onFiles(event.target.files)}
        />
        {isLoading && (
          <div className="mt-2 text-xs uppercase tracking-[0.3em] text-indigo-300">
            Parsing…
          </div>
        )}
      </label>
      <div className="mt-6 rounded-lg border border-white/10 bg-black/20 p-4 text-sm text-slate-200">
        {status}
      </div>
      {error && (
        <div className="mt-3 rounded-lg border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-200">
          {error}
        </div>
      )}
    </div>
  );
}

type VerificationPanelProps = {
  detectedGroup: string | null;
  overrideGroup: string;
  onOverrideChange: (value: string) => void;
  autoMatches: boolean;
  overrideMatches: boolean;
};

function VerificationPanel({
  detectedGroup,
  overrideGroup,
  onOverrideChange,
  autoMatches,
  overrideMatches,
}: VerificationPanelProps) {
  const statusColor = autoMatches || overrideMatches ? "text-emerald-300" : "text-amber-300";
  const statusLabel =
    autoMatches || overrideMatches
      ? "Zero to One confirmed"
      : "Awaiting confirmation";

  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className={`text-sm font-medium uppercase tracking-[0.35em] ${statusColor}`}>
            {statusLabel}
          </p>
          <h2 className="mt-2 text-2xl font-semibold text-white">
            Group verification
          </h2>
          <p className="mt-1 text-sm text-slate-300">
            If the detected name is different, confirm the{" "}
            <strong>Zero to One</strong> label to proceed.
          </p>
        </div>
        <div className="rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-200">
          Detected:{" "}
          <span className="font-semibold text-white">
            {detectedGroup ?? "Not available"}
          </span>
        </div>
      </div>
      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center">
        <label
          htmlFor="group-override"
          className="text-sm font-medium text-slate-200 sm:w-48"
        >
          Confirm group name
        </label>
        <input
          id="group-override"
          type="text"
          value={overrideGroup}
          onChange={(event) => onOverrideChange(event.target.value)}
          className="flex-1 rounded-lg border border-white/10 bg-black/40 px-4 py-2 text-sm text-white outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/40"
        />
      </div>
    </div>
  );
}

type ConversationPanelProps = {
  fileName: string;
  chat: ParsedChat;
  filterQuery: string;
  onFilterChange: (value: string) => void;
  participants: string[];
  selectedAuthors: string[];
  onSelectionChange: (values: string[]) => void;
  messages: WhatsAppMessage[];
  onDownload: () => void;
};

function ConversationPanel({
  fileName,
  chat,
  filterQuery,
  onFilterChange,
  participants,
  selectedAuthors,
  onSelectionChange,
  messages,
  onDownload,
}: ConversationPanelProps) {
  const toggleAuthor = (name: string) => {
    if (selectedAuthors.includes(name)) {
      onSelectionChange(selectedAuthors.filter((author) => author !== name));
    } else {
      onSelectionChange([...selectedAuthors, name]);
    }
  };

  return (
    <div className="space-y-6">
      <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div>
            <h2 className="text-2xl font-semibold text-white">
              {chat.groupName ?? TARGET_GROUP}
            </h2>
            <p className="mt-1 text-sm text-slate-300">
              {chat.stats.totalMessages.toLocaleString()} messages ·{" "}
              {participants.length} participants · File:{" "}
              <span className="font-medium text-white">{fileName}</span>
            </p>
          </div>
          <button
            onClick={onDownload}
            className="inline-flex items-center justify-center rounded-lg border border-indigo-400/50 bg-indigo-500/20 px-4 py-2 text-sm font-medium text-indigo-100 transition hover:border-indigo-300 hover:bg-indigo-400/30"
          >
            Export filtered JSON
          </button>
        </div>
        <dl className="mt-6 grid gap-4 rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-slate-200 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <dt className="text-slate-400">First message</dt>
            <dd className="mt-1 font-medium text-white">
              {formatDate(chat.stats.firstMessage)}
            </dd>
          </div>
          <div>
            <dt className="text-slate-400">Latest message</dt>
            <dd className="mt-1 font-medium text-white">
              {formatDate(chat.stats.lastMessage)}
            </dd>
          </div>
          <div>
            <dt className="text-slate-400">Authored entries</dt>
            <dd className="mt-1 font-medium text-white">
              {chat.stats.authoredMessages.toLocaleString()}
            </dd>
          </div>
          <div>
            <dt className="text-slate-400">System notices</dt>
            <dd className="mt-1 font-medium text-white">
              {chat.stats.systemMessages.toLocaleString()}
            </dd>
          </div>
        </dl>
      </div>

      <div className="grid gap-6 lg:grid-cols-[280px_1fr]">
        <div className="space-y-6">
          <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <label
              htmlFor="search"
              className="text-sm font-medium text-slate-200"
            >
              Search messages
            </label>
            <input
              id="search"
              type="text"
              value={filterQuery}
              onChange={(event) => onFilterChange(event.target.value)}
              placeholder="Search for keywords or people"
              className="mt-2 w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-sm text-white outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/40"
            />
          </div>

          <div className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <span className="text-sm font-medium text-slate-200">
              Participants
            </span>
            <div className="mt-3 space-y-2 text-sm text-slate-200">
              {participants.length ? (
                participants.map((participant) => {
                  const count = chat.messages.filter(
                    (message) => message.author === participant
                  ).length;
                  const isSelected = selectedAuthors.includes(participant);
                  return (
                    <label
                      key={participant}
                      className="flex items-center gap-2 rounded-lg border border-white/5 bg-black/20 px-3 py-2 transition hover:border-indigo-400/40"
                    >
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleAuthor(participant)}
                        className="size-4 rounded border-white/20 bg-black/60 text-indigo-400 focus:ring-indigo-400"
                      />
                      <span className="flex-1">
                        <span className="font-medium text-white">
                          {participant}
                        </span>
                        <span className="ml-2 text-xs text-slate-400">
                          {count.toLocaleString()} messages
                        </span>
                      </span>
                    </label>
                  );
                })
              ) : (
                <p className="text-sm text-slate-400">
                  Participant names will appear after parsing the chat.
                </p>
              )}
            </div>
            {selectedAuthors.length > 0 && (
              <button
                onClick={() => onSelectionChange([])}
                className="mt-3 text-xs font-medium text-indigo-200 underline underline-offset-4"
              >
                Clear selection
              </button>
            )}
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5">
          <header className="flex items-center justify-between border-b border-white/10 px-6 py-4 text-sm text-slate-300">
            <span>{messages.length.toLocaleString()} messages shown</span>
            <span>Newest first</span>
          </header>
          <MessageList messages={messages} />
        </div>
      </div>
    </div>
  );
}

type MessageListProps = {
  messages: WhatsAppMessage[];
};

function MessageList({ messages }: MessageListProps) {
  if (!messages.length) {
    return (
      <div className="flex h-64 items-center justify-center px-6 text-sm text-slate-400">
        No messages match your filters yet.
      </div>
    );
  }

  return (
    <ul className="max-h-[32rem] space-y-4 overflow-y-auto px-6 py-5 text-sm leading-relaxed text-slate-100">
      {[...messages]
        .sort((a, b) => {
          const left = a.timestamp?.getTime() ?? 0;
          const right = b.timestamp?.getTime() ?? 0;
          return right - left;
        })
        .map((message) => (
          <li
            key={`${message.timestamp?.toISOString() ?? message.raw}-${message.author ?? "system"}`}
            className="rounded-xl border border-white/5 bg-black/20 p-4"
          >
            <div className="flex items-center justify-between text-xs text-slate-400">
              <span className="font-semibold text-indigo-200">
                {message.author ?? "System"}
              </span>
              <time>{formatShortDate(message.timestamp)}</time>
            </div>
            <p className="mt-3 whitespace-pre-wrap text-sm text-slate-100">
              {message.text}
            </p>
            {message.isSystem && (
              <span className="mt-3 inline-flex items-center rounded-full bg-amber-500/20 px-3 py-1 text-[11px] font-semibold uppercase tracking-widest text-amber-200">
                System
              </span>
            )}
          </li>
        ))}
    </ul>
  );
}

function MismatchNotice() {
  return (
    <div className="rounded-2xl border border-amber-400/30 bg-amber-500/10 p-6 text-sm text-amber-100">
      <h3 className="text-xl font-semibold text-amber-200">
        Waiting for the Zero to One export
      </h3>
      <p className="mt-2 text-sm">
        The uploaded file does not look like the <strong>Zero to One</strong>
        chat yet. Double-check that you exported the correct group or confirm
        the name in the verification panel above. Once confirmed, the full
        conversation will appear here.
      </p>
    </div>
  );
}
